### ISSUE TITLE
log4jna demo app does not log messages to Windows Event Viewer

### ISSUE THREAD

**Issue by SpartaSixZero** [dblock/log4jna#8] opened 2016-04-21 13:00 UTC
I wanted to test out log4jna so I followed the steps from here: https://github.com/dblock/log4jna/blob/master/doc/org.apache.log4jna.nt.Win32EventLogAppender.md

Right now, I have a very simple java app (slightly modified demo app). Here is the code:

```
package log4jnawithoutmaven;

import org.apache.log4j.LogManager;
import org.apache.log4j.Logger;

public class Log4jnaWithoutMavenDemo {
    public static void main(String[] args) {
        try {
//          PropertyConfigurator.configureAndWatch("log4j.properties");
            Logger logger = LogManager.getLogger(Log4jnaWithoutMavenDemo.class);
            String debug_message = "debug: we got a bug here";
            String info_message = "info info info";

            logger.debug("debug: " + debug_message);
            logger.info("info: " + info_message);
            System.out.println(debug_message);
            System.out.println(info_message);
        } catch (Throwable t) {
            System.out.println("encountered error!");
            t.printStackTrace();
            System.exit(1);         
        }
    }
}
```

Below is my log4j.properties file:

```
log4j.rootCategory=E, S

org.apache.log4jna.nt.demo=DEBUG

log4j.appender.S = org.apache.log4j.ConsoleAppender
log4j.appender.S.layout = org.apache.log4j.PatternLayout
log4j.appender.S.layout.ConversionPattern = %d{yyyy-MM-dd HH:mm:ss} %c{1} [%p] %m%n

log4j.appender.E = org.apache.log4jna.nt.Win32EventLogAppender
log4j.appender.E.layout = org.apache.log4j.PatternLayout
log4j.appender.E.source = demo
log4j.appender.E.layout.ConversionPattern = %d{yyyy-MM-dd HH:mm:ss} %c{1} [%p] %m%n
```

Below is my log4j.xml file:

```
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE log4j:configuration SYSTEM "log4j.dtd">

<log4j:configuration xmlns:log4j='http://jakarta.apache.org/log4j/'>

    <appender name="console" class="org.apache.log4j.ConsoleAppender">
        <param name="Target" value="System.out" />
        <layout class="org.apache.log4j.PatternLayout">
            <param name="ConversionPattern" value="%-5p [%t] %m%n" />
        </layout>
    </appender>

    <appender name="WINDOWS" class="org.apache.log4jna.nt.Win32EventLogAppender">

        <param name="source" value="MyLogs" />
        <param name="application" value="TestApp" />
        <param name="eventMessageFile"
            value="E:\\log4jna\\Win32EventLogAppender.dll" />
        <param name="categoryMessageFile"
            value="E:\\log4jna\\Win32EventLogAppender.dll" />

        <layout class="org.apache.log4j.PatternLayout">
            <param name="ConversionPattern" value="%-5p [%t] %m%n" />
        </layout>
    </appender>

    <root>
        <!--<priority value="info" />-->
        <appender-ref ref="WINDOWS" />
        <appender-ref ref="console" />
    </root>
</log4j:configuration>
```

Here is my .classpath file:

```
<?xml version="1.0" encoding="UTF-8"?>
<classpath>
    <classpathentry kind="src" path="src"/>
    <classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.7"/>
    <classpathentry kind="lib" path="E:/log4jna/jna.jar"/>
    <classpathentry kind="lib" path="E:/log4jna/log4jna.jar"/>
    <classpathentry kind="lib" path="E:/log4jna/platform.jar"/>
    <classpathentry kind="lib" path="E:/log4j/v1.0/log4j-1.2.17.jar"/>
    <classpathentry kind="output" path="bin"/>
</classpath>
```

When I run my application, I can see the following messages appear in my console:

```
DEBUG [main] debug: debug: we got a bug here
INFO  [main] info: info info info
debug: we got a bug here
info info info
```

However, nothing ever shows in Event Viewer. Note: I'm using log4j 1.X because currently, log4jna does not support log4j 2.X.

I made sure that my registry editor contains the correct settings:

`HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\eventlog\Application\Log4jna `

```
CategoryCount is REG_DWORD 6
CategoryMessageFile is REG_SZ E:\log4jna\Win32EventLogAppender.dll
EventMessageFile is REG_SZ E:\log4jna\Win32EventLogAppender.dll
TypesSupported is REG_DWORD 7
```

**Comment by dblock** [comment] 2016-04-21 21:41
Nothing wrong I see here. Are you looking in the right log? I mean "Application"? Does http://code.dblock.org/2010/10/14/log4jna-log4jerror-could-not-register-event-source-access-is-denied.html help at all.

**Comment by SpartaSixZero** [comment] 2016-04-22 12:31
Yes I did look at the Application event logs. I never got any errors like the post in that link. 

Yesterday, I did create another demo app using just JNA alone and actually succeeded in writing a message to the Windows Event Viewer. I created a basic Java Maven add and included the two dependencies for jna-4.2.2 and jna-platform-4.2.2. Then I used the registry step from here https://github.com/dblock/log4jna/blob/master/doc/org.apache.log4jna.nt.Win32EventLogAppender.md and it just worked. 

Here is my main code:

```
import com.sun.jna.*;
import com.sun.jna.win32.*;
import com.sun.jna.platform.win32.*;
import com.sun.jna.platform.win32.WinNT.HANDLE;

public class jnaapp 
{
    public static void main( String[] args )
    {
    	Advapi32 advapi = Advapi32.INSTANCE;
    	HANDLE event_handle =  advapi.RegisterEventSource(null, "log4jna");
    	
        String[] message_array = new String[1];
        message_array[0] = "Error code: 1003 - Sample error message";
        
        boolean success = false;
        success = advapi.ReportEvent(event_handle, 1, 1, 1, null, message_array.length, 0, message_array, null);
        		
        System.out.println("Status of report event method: " + success);		
    }
}
```

**Comment by dblock** [comment] 2016-04-22 13:34
Did you try the demo app that comes with this project, as is?

**Comment by SpartaSixZero** [comment] 2016-04-22 13:44
Yes I have, but I was still not seeing the messages sent to Event Viewer. No worries, I'll just use JNA for now.

**Comment by claudiow** [comment] 2016-07-12 19:31
This has been fixed for release of 2.0

**Comment by dblock** [comment] 2016-07-12 20:44
@claudiow What's the actual root cause of this?

**Comment by claudiow** [comment] 2016-07-12 21:48
I think that it is just a configuration problem:

@SpartaSixZero is using the  `.properties` configuration and...

The registry key is 
`HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\eventlog\Application\Log4jna `

Based in `log4j.appender.E.source = demo` It should be
`HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\eventlog\Application\demo`
The logs will show in `EventViewer->Application->demo`

or `log4j.appender.E.source = Log4Jna`  and `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\eventlog\Application\Log4jna`
The logs will show in `EventViewer->Application->Log4jna`

Regarding the .xml configuration this is what I mentioned in #6 the code expects `log` and @SpartaSixZero file uses `application` and the parameters do not match the registry.
 
```xml
<appender name="WINDOWS" class="org.apache.log4jna.nt.Win32EventLogAppender">

        <param name="source" value="MyLogs" /> <!-- Thsi should be Log4Jna -->
        <param name="application" value="TestApp" /> <!-- This should be Application or not present and named log-->
        <param name="eventMessageFile"
            value="E:\\log4jna\\Win32EventLogAppender.dll" /> <!-- This was ignore in version 1.3 as the code did not expected the parameters, I added this a few days ago -->
        <param name="categoryMessageFile"
            value="E:\\log4jna\\Win32EventLogAppender.dll" /> <!-- Idem than above -->

        <layout class="org.apache.log4j.PatternLayout">
            <param name="ConversionPattern" value="%-5p [%t] %m%n" />
        </layout>
    </appender>
```

**Comment by dblock** [comment] 2016-07-13 12:52
This makes a lot of sense, thanks @claudiow. I'll close this, @SpartaSixZero do let us know if that didn't help.

**Closed by dblock** 2016-07-13 12:52 UTC
Labels: bug?
